"""empty message

Revision ID: 295a9c77571c
Revises: 
Create Date: 2023-06-26 15:38:03.037941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295a9c77571c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Translations',
    sa.Column('id', sa.String(length=130), nullable=False),
    sa.Column('user_id', sa.String(length=130), nullable=False),
    sa.Column('original_image', sa.String(length=130), nullable=True),
    sa.Column('filename', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Translations')
    op.drop_table('User')
    # ### end Alembic commands ###
